// apps/crud/preact/src/pages/TaskCreate.tsx
import { useState, useEffect } from 'preact/hooks'
import { route } from 'preact-router'
import { createTask, fetchCategories } from '../api'
import TaskForm from '../components/TaskForm'
import type { TaskFormData } from '../schemas/task'
import type { Category } from '../../../../../shared/types'

export default function TaskCreate() {
  const [categories, setCategories] = useState<Category[]>([])
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    fetchCategories().then(setCategories)
  }, [])

  const handleSubmit = async (data: TaskFormData) => {
    setSubmitting(true)
    try {
      await createTask(data)
      route('/tasks')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div>
      <h1 class="text-2xl font-bold text-gray-900 mb-6">Create Task</h1>
      <TaskForm
        categories={categories}
        onSubmit={handleSubmit}
        isSubmitting={submitting}
      />
    </div>
  )
}

// apps/crud/solid/src/pages/TaskCreate.tsx
import { createResource, createSignal } from 'solid-js'
import { useNavigate } from '@solidjs/router'
import { createTask, fetchCategories } from '../api/tasks'
import TaskForm from '../components/TaskForm'
import type { TaskFormData } from '../schemas/task'

export default function TaskCreate() {
  const navigate = useNavigate()
  const [categories] = createResource(fetchCategories)
  const [isSubmitting, setIsSubmitting] = createSignal(false)

  const handleSubmit = async (data: TaskFormData) => {
    setIsSubmitting(true)
    try {
      await createTask(data)
      navigate('/tasks')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div>
      <h1 class="text-2xl font-bold text-gray-900 mb-6">Create Task</h1>
      <TaskForm
        categories={categories() || []}
        onSubmit={handleSubmit}
        isSubmitting={isSubmitting()}
      />
    </div>
  )
}
