// apps/crud/react/src/components/TaskForm.tsx
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { taskSchema, type TaskFormData } from '../schemas/task'
import type { Category, Task } from '../../../../../shared/types'

interface Props {
  categories: Category[]
  defaultValues?: Partial<TaskFormData>
  onSubmit: (data: TaskFormData) => void
  isSubmitting?: boolean
}

export default function TaskForm({ categories, defaultValues, onSubmit, isSubmitting }: Props) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<TaskFormData>({
    resolver: zodResolver(taskSchema),
    defaultValues: {
      title: '',
      description: '',
      status: 'pending',
      priority: 'medium',
      categoryId: 1,
      ...defaultValues,
    },
  })

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4 max-w-lg">
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Title</label>
        <input {...register('title')} className="w-full px-3 py-2 border rounded text-sm" />
        {errors.title && <p className="text-red-500 text-xs mt-1">{errors.title.message}</p>}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
        <textarea {...register('description')} rows={3} className="w-full px-3 py-2 border rounded text-sm" />
        {errors.description && <p className="text-red-500 text-xs mt-1">{errors.description.message}</p>}
      </div>

      <div className="grid grid-cols-3 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
          <select {...register('status')} className="w-full px-3 py-2 border rounded text-sm bg-white">
            <option value="pending">Pending</option>
            <option value="in-progress">In Progress</option>
            <option value="done">Done</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Priority</label>
          <select {...register('priority')} className="w-full px-3 py-2 border rounded text-sm bg-white">
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
          <select {...register('categoryId')} className="w-full px-3 py-2 border rounded text-sm bg-white">
            {categories.map((c) => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </div>
      </div>

      <button
        type="submit"
        disabled={isSubmitting}
        className="px-6 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:opacity-50"
      >
        {isSubmitting ? 'Saving...' : 'Save Task'}
      </button>
    </form>
  )
}

// apps/crud/svelte/src/lib/components/TaskForm.svelte
<script lang="ts">
  import { taskSchema, type TaskFormData } from '../schemas/task'
  import type { Category } from '../../../../../shared/types'

  let { categories, defaultValues, isSubmitting = false, onsubmit: onsubmitProp }: {
    categories: Category[]
    defaultValues?: Partial<TaskFormData>
    isSubmitting?: boolean
    onsubmit: (data: TaskFormData) => void
  } = $props()

  let form = $state<TaskFormData>({
    title: defaultValues?.title || '',
    description: defaultValues?.description || '',
    status: defaultValues?.status || 'pending',
    priority: defaultValues?.priority || 'medium',
    categoryId: defaultValues?.categoryId || 1,
  })

  let errors = $state<Record<string, string>>({})

  function handleSubmit(e: Event) {
    e.preventDefault()
    const result = taskSchema.safeParse(form)
    if (!result.success) {
      errors = {}
      for (const issue of result.error.issues) {
        errors[issue.path[0] as string] = issue.message
      }
      return
    }
    errors = {}
    onsubmitProp(result.data)
  }
</script>

<form onsubmit={handleSubmit} class="space-y-4 max-w-lg">
  <div>
    <label class="block text-sm font-medium text-gray-700 mb-1">Title</label>
    <input bind:value={form.title} class="w-full px-3 py-2 border rounded text-sm" />
    {#if errors.title}<p class="text-red-500 text-xs mt-1">{errors.title}</p>{/if}
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700 mb-1">Description</label>
    <textarea bind:value={form.description} rows={3} class="w-full px-3 py-2 border rounded text-sm"></textarea>
    {#if errors.description}<p class="text-red-500 text-xs mt-1">{errors.description}</p>{/if}
  </div>

  <div class="grid grid-cols-3 gap-4">
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Status</label>
      <select bind:value={form.status} class="w-full px-3 py-2 border rounded text-sm bg-white">
        <option value="pending">Pending</option>
        <option value="in-progress">In Progress</option>
        <option value="done">Done</option>
      </select>
    </div>
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Priority</label>
      <select bind:value={form.priority} class="w-full px-3 py-2 border rounded text-sm bg-white">
        <option value="low">Low</option>
        <option value="medium">Medium</option>
        <option value="high">High</option>
      </select>
    </div>
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Category</label>
      <select bind:value={form.categoryId} class="w-full px-3 py-2 border rounded text-sm bg-white">
        {#each categories as c}
          <option value={c.id}>{c.name}</option>
        {/each}
      </select>
    </div>
  </div>

  <button type="submit" disabled={isSubmitting}
    class="px-6 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:opacity-50">
    {isSubmitting ? 'Saving...' : 'Save Task'}
  </button>
</form>
