// apps/crud/react/src/components/TaskFilters.tsx
import { useTaskStore } from '../store/task-store'
import type { Category } from '../../../../../shared/types'

interface Props {
  categories: Category[]
}

export default function TaskFilters({ categories }: Props) {
  const { filters, setFilter, resetFilters } = useTaskStore()

  return (
    <div className="flex flex-wrap gap-3 items-center mb-6">
      <select
        value={filters.status || 'all'}
        onChange={(e) => setFilter('status', e.target.value as any)}
        className="px-3 py-2 border rounded text-sm bg-white"
      >
        <option value="all">All Status</option>
        <option value="pending">Pending</option>
        <option value="in-progress">In Progress</option>
        <option value="done">Done</option>
      </select>

      <select
        value={filters.categoryId || ''}
        onChange={(e) => setFilter('categoryId', e.target.value ? Number(e.target.value) : undefined)}
        className="px-3 py-2 border rounded text-sm bg-white"
      >
        <option value="">All Categories</option>
        {categories.map((c) => (
          <option key={c.id} value={c.id}>{c.name}</option>
        ))}
      </select>

      <select
        value={filters.sortBy || 'createdAt'}
        onChange={(e) => setFilter('sortBy', e.target.value as any)}
        className="px-3 py-2 border rounded text-sm bg-white"
      >
        <option value="createdAt">Date Created</option>
        <option value="title">Title</option>
        <option value="priority">Priority</option>
      </select>

      <button
        onClick={() => setFilter('sortOrder', filters.sortOrder === 'asc' ? 'desc' : 'asc')}
        className="px-3 py-2 border rounded text-sm bg-white hover:bg-gray-50"
      >
        {filters.sortOrder === 'asc' ? '↑ Asc' : '↓ Desc'}
      </button>

      <button
        onClick={resetFilters}
        className="px-3 py-2 text-sm text-gray-500 hover:text-gray-700"
      >
        Reset
      </button>
    </div>
  )
}

// apps/crud/vue/src/components/TaskFilters.vue
<script setup lang="ts">
import { useTaskStore } from '../stores/task-store'
import type { Category } from '../../../../../shared/types'

defineProps<{ categories: Category[] }>()

const store = useTaskStore()
</script>

<template>
  <div class="flex flex-wrap gap-3 items-center mb-6">
    <select :value="store.filters.status || 'all'" @change="store.setFilter('status', ($event.target as HTMLSelectElement).value as any)"
      class="px-3 py-2 border rounded text-sm bg-white">
      <option value="all">All Status</option>
      <option value="pending">Pending</option>
      <option value="in-progress">In Progress</option>
      <option value="done">Done</option>
    </select>

    <select :value="store.filters.categoryId || ''" @change="store.setFilter('categoryId', ($event.target as HTMLSelectElement).value ? Number(($event.target as HTMLSelectElement).value) : undefined)"
      class="px-3 py-2 border rounded text-sm bg-white">
      <option value="">All Categories</option>
      <option v-for="c in categories" :key="c.id" :value="c.id">{{ c.name }}</option>
    </select>

    <select :value="store.filters.sortBy || 'createdAt'" @change="store.setFilter('sortBy', ($event.target as HTMLSelectElement).value as any)"
      class="px-3 py-2 border rounded text-sm bg-white">
      <option value="createdAt">Date Created</option>
      <option value="title">Title</option>
      <option value="priority">Priority</option>
    </select>

    <button @click="store.setFilter('sortOrder', store.filters.sortOrder === 'asc' ? 'desc' : 'asc')"
      class="px-3 py-2 border rounded text-sm bg-white hover:bg-gray-50">
      {{ store.filters.sortOrder === 'asc' ? '↑ Asc' : '↓ Desc' }}
    </button>

    <button @click="store.resetFilters" class="px-3 py-2 text-sm text-gray-500 hover:text-gray-700">
      Reset
    </button>
  </div>
</template>
